### ISSUE TITLE
Conditional display partially working

### ISSUE THREAD

**Issue by Castelvielh** [lsmarsden/bubble-card-modules#1]
Hello,

Thank you first for the additional features, though I have an issue with with the conditional display of the icon progress border. If the condition to display a progress border becomes true, this progress border correctly shows up, whereas when the same condition becomes false again, the progress border stays and only a home assistant web page refresh gets back to the correct situation where the progress border is not shown. It seems like once the condition is met, it is never checked again.

Here is a YAML example with a condition:

```
type: custom:bubble-card
card_type: button
button_type: switch
entity: fan.mi_standing_fan
show_attribute: true
attribute: percentage
show_state: true
icon_border_progress:
  - button: main
    source: fan.mi_standing_fan[percentage]
    condition:
      - condition: state
        entity_id: fan.mi_standing_fan
        state: "on"
modules:
  - icon_border_progress
```
